### ISSUE TITLE
[Feature]: Installation guide

### ISSUE THREAD

**Issue by krzwiatrzyk** [govirtuo/kube-ns-suspender#77]
### Is your feature request related to a problem?

Hi, I have tried to install `kube-ns-suspender` on my K3d cluster to test it out however it is very difficult to sort it out how to do it. 
Additionally, I want to install `kube-ns-suspender` without cloning the repo and using Kustomize and I think it is not possible yet?

### Describe the solution you'd like

A clear and concise description of how to install `kube-ns-suspender` on the cluster

**Comment by eze-kiel** [comment]
Hi @krzwiatrzyk, thanks for raising this issue. You're right, the installation guide is lacking. We'll try to find the time to improve the documentation.
