### ISSUE TITLE
[Feature]: Support pausing Keda autoscaling

### ISSUE THREAD

**Issue by apapia** [govirtuo/kube-ns-suspender#88]
### Is your feature request related to a problem?

I use [Keda](https://keda.sh/) to autoscale some components.  Keda runs in its own namespace.  Unfortunately, when I suspend a namespace that includes Keda ScaledObjects, Keda will continue to try to scale up the deployment in the suspended namespace.  

### Describe the solution you'd like

In order to avoid this, the ScaledObject resources can be annotated to pause autoscaling.  See:
https://keda.sh/docs/2.8/concepts/scaling-deployments/#pause-autoscaling

If a namespace is suspended, check if any apiVersion: keda.sh/v1alpha1, kind: ScaledObject resources exist in the namespace.  If they do, add the autoscaling.keda.sh/paused-replicas: "0" annotation.  When the namespace is unsuspended, remove this annotation.

**Comment by eze-kiel** [comment]
Resolved by `v2.4.0`
