### ISSUE TITLE
[Bug]: Failed to unsuspend deployment scaled to 0

### ISSUE THREAD

**Issue by apapia** [govirtuo/kube-ns-suspender#90]
### Version

v2.1.1

### What happened?

I have a deployment of pods that is scaled to 0 by Keda.  When I suspend the namespace, the deployment isn't annotated with the originalReplicas, presumably because it is scaled to 0.  When I unsuspend the namespace, I hit an error because the originalReplicas annotation is missing.

### Relevant log output

```bash
{"level":"debug","routine":"suspender","namespace":"cogito-saas","step":"3/3 - handle desiredState","resource":"statefulsets","time":"2022-12-19T16:07:14+01:00","message":"checking running conformity"}
{"level":"error","routine":"suspender","namespace":"cogito-saas","error":"strconv.Atoi: parsing \"\": invalid syntax","time":"2022-12-19T16:07:14+01:00","message":"running deployments conformity checks failed"}
```

**Comment by apapia** [comment]
Reproduced by setting `replicas: 0` in the e2e tests and observing the error in the logs:
https://github.com/govirtuo/kube-ns-suspender/blob/main/manifests/testing-namespace/full.yaml#L55

**Comment by eze-kiel** [comment]
Hi @apapia, thanks for opening an issue. I'll try to have a look ASAP.

**Comment by eze-kiel** [comment]
Thanks for your PR @apapia! Your patch will be present in the `v2.3.1` in a few minutes.
