### ISSUE TITLE
[Feature]: Align namespace names to the left

### ISSUE THREAD

**Issue by motet-a** [govirtuo/kube-ns-suspender#94]
### Is your feature request related to a problem?

It’s not related to a problem. It’s a suggestion of a design update.

### Describe the solution you'd like

Currently, namespace names are centered:

<img width="474" alt="image" src="https://user-images.githubusercontent.com/15378830/212031611-66d31c7a-686d-418d-a756-8b63fbd0dbbe.png">

I suggest to align them to the left:

<img width="474" alt="image" src="https://user-images.githubusercontent.com/15378830/212031802-2a2f3db5-44e7-4113-869f-61a59ea2607b.png">

I think it makes easier to spot the important parts of the names when some of the namespace names start with the same prefix.

**Comment by eze-kiel** [comment]
hi @motet-a, thanks for opening an issue.

I do not know about your idea, as this naming convention (`feature-xyz`) is highly tied to our internal usage.

**Comment by motet-a** [comment]
Yes! But since I don’t see how left-aligned text could be annoying for people that don’t use common prefixes… I think it’s worth changing it.

BTW I think it’s pretty uncommon to center text in tables, in general. To me, centering text is mostly used for title or a description you’ll find under a picture, for instance.

**Comment by eze-kiel** [comment]
Okay, I got it. I'll open a PR and keep you posted!
